AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '.wercker/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/RescueStandardError:
  Exclude:
    - 'lib/object/cache.rb'
    - 'test/cache_test.rb'

Security/MarshalLoad:
  Exclude:
    - 'lib/object/cache.rb'
    - 'test/cache_test.rb'
