AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '.wercker/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'lib/object/cache.rb'
    - 'test/cache_test.rb'

Security/MarshalLoad:
  Exclude:
    - 'lib/object/cache.rb'
    - 'test/cache_test.rb'
